require('core.config.interface.treesitter')
require('core.config.interface.lualine')
require('core.config.interface.whichkey.config')
require('core.config.interface.whichkey.mappings')
require('core.config.interface.bufferline')
require('core.config.interface.dressing')
require('core.config.interface.notify')
require('core.config.interface.neotree')
-- require('core.config.interface.nvim-tree')
